INSERT INTO action_codes (code, description) VALUES ('0042', 'Landscape Gardening');
INSERT INTO action_codes (code, description) VALUES ('5020', 'Ceiling Installation');
INSERT INTO action_codes (code, description) VALUES ('5027', 'Masonry–low wage');
INSERT INTO action_codes (code, description) VALUES ('5028', 'Masonry–high wage');
INSERT INTO action_codes (code, description) VALUES ('5029', 'Concrete Sawing/Drilling');
INSERT INTO action_codes (code, description) VALUES ('5040(1)', 'Iron/Steel Erection–structural');
INSERT INTO action_codes (code, description) VALUES ('5040(2)', 'Bridge Building–metal');
INSERT INTO action_codes (code, description) VALUES ('5040(3)', 'Painting–steel structures/bridges');
INSERT INTO action_codes (code, description) VALUES ('5057', 'Iron/Steel Erection–N.O.C.');
INSERT INTO action_codes (code, description) VALUES ('5059', 'Iron/Steel Erection–buildings <3 stories ');
INSERT INTO action_codes (code, description) VALUES ('5102(1)', 'Iron/Steel Erection–non-structural ');
INSERT INTO action_codes (code, description) VALUES ('5102(3)', 'Floor Installation');
INSERT INTO action_codes (code, description) VALUES ('5107', 'Door/Pre-Glazed Window Installation');
INSERT INTO action_codes (code, description) VALUES ('5108', 'Door Installation–overhead doors');
INSERT INTO action_codes (code, description) VALUES ('5140', 'Electrical Wiring–high wage');
INSERT INTO action_codes (code, description) VALUES ('5146(1)', 'Cabinet/Fixtures Installation');
INSERT INTO action_codes (code, description) VALUES ('5146(2)', 'Sign Installation/Repair ');
INSERT INTO action_codes (code, description) VALUES ('5160', 'Elevator Erection/Repair');
INSERT INTO action_codes (code, description) VALUES ('5183(1)', 'Plumbing–low wage');
INSERT INTO action_codes (code, description) VALUES ('5183(2)', 'Refrigeration Equip–low wage');
INSERT INTO action_codes (code, description) VALUES ('5184', 'Steam Pipe/Boiler Insulation');
INSERT INTO action_codes (code, description) VALUES ('5185', 'Automatic Sprinkler Install–low wage');
INSERT INTO action_codes (code, description) VALUES ('5186', 'Automatic Sprinkler Install–high wage');
INSERT INTO action_codes (code, description) VALUES ('5187(1)', 'Plumbing–high wage');
INSERT INTO action_codes (code, description) VALUES ('5187(2)', 'Refrigeration Equipment–high wage');
INSERT INTO action_codes (code, description) VALUES ('5190', 'Electrical Wiring–low wage');
INSERT INTO action_codes (code, description) VALUES ('5191(1)', 'Office Machine Installation/Repair');
INSERT INTO action_codes (code, description) VALUES ('5191(2)', 'Computer/System Installation/Repair');
INSERT INTO action_codes (code, description) VALUES ('5191(3)', 'Telephone/System Installation/Repair');
INSERT INTO action_codes (code, description) VALUES ('5195', 'Communications Cabling');
INSERT INTO action_codes (code, description) VALUES ('5201(1)', 'Concrete/Cement Work–sidewalks–low wage');
INSERT INTO action_codes (code, description) VALUES ('5201(2)', 'Concrete/Cement Work–low wage');
INSERT INTO action_codes (code, description) VALUES ('5205(1)', 'Concrete/Cement Work–sidewalks–high wage');
INSERT INTO action_codes (code, description) VALUES ('5205(2)', 'Concrete/Cement Work–high wage');
INSERT INTO action_codes (code, description) VALUES ('5212', 'Concrete Pumping–foundations');
INSERT INTO action_codes (code, description) VALUES ('5213', 'Concrete Construction');
INSERT INTO action_codes (code, description) VALUES ('5214', 'Concrete/Cement Work–precast');
INSERT INTO action_codes (code, description) VALUES ('5222(1)', 'Concrete Construction–bridges');
INSERT INTO action_codes (code, description) VALUES ('5222(2)', 'Chimney Construction');
INSERT INTO action_codes (code, description) VALUES ('5225', 'Reinforcing Steel Installation');
INSERT INTO action_codes (code, description) VALUES ('5348', 'Tile/Stone/Mosaic/Terrazzo Work');
INSERT INTO action_codes (code, description) VALUES ('5403', 'Carpentry–low wage');
INSERT INTO action_codes (code, description) VALUES ('5432', 'Carpentry–high wage');
INSERT INTO action_codes (code, description) VALUES ('5436', 'Hardwood Floor Laying');
INSERT INTO action_codes (code, description) VALUES ('5443', 'Lathing');
INSERT INTO action_codes (code, description) VALUES ('5446', 'Wallboard Application–low wage');
INSERT INTO action_codes (code, description) VALUES ('5447', 'Wallboard Application–high wage');
INSERT INTO action_codes (code, description) VALUES ('5467', 'Glaziers–low wage');
INSERT INTO action_codes (code, description) VALUES ('5470', 'Glaziers–high wage');
INSERT INTO action_codes (code, description) VALUES ('5473', 'Asbestos Abatement');
INSERT INTO action_codes (code, description) VALUES ('5474(1)', 'Painting/Decorating–low wage');
INSERT INTO action_codes (code, description) VALUES ('5474(2)', 'Waterproofing–low wage');
INSERT INTO action_codes (code, description) VALUES ('5474(3)', 'Painting–oil/gas storage tanks–low wage');
INSERT INTO action_codes (code, description) VALUES ('5479', 'Insulation Work');
INSERT INTO action_codes (code, description) VALUES ('5482(1)', 'Painting/Decorating–high wage');
INSERT INTO action_codes (code, description) VALUES ('5482(2)', 'Waterproofing–high wage');
INSERT INTO action_codes (code, description) VALUES ('5482(3)', 'Painting–oil/gas–storage tanks–high wage');
INSERT INTO action_codes (code, description) VALUES ('5484', 'Plastering/Stucco Work–low wage');
INSERT INTO action_codes (code, description) VALUES ('5485', 'Plastering/Stucco Work–high wage');
INSERT INTO action_codes (code, description) VALUES ('5506', 'Street/Road Construction–paving');
INSERT INTO action_codes (code, description) VALUES ('5507', 'Street/Road Construction–grading');
INSERT INTO action_codes (code, description) VALUES ('5538', 'Sheet Metal Work–low wage ');
INSERT INTO action_codes (code, description) VALUES ('5542', 'Sheet Metal Work–high wage');
INSERT INTO action_codes (code, description) VALUES ('5552', 'Roofing–low wage');
INSERT INTO action_codes (code, description) VALUES ('5553', 'Roofing–high wage');
INSERT INTO action_codes (code, description) VALUES ('5606', 'Contractors–executive level supervisors');
INSERT INTO action_codes (code, description) VALUES ('5632', 'Steel Framing–light gauge–low wage');
INSERT INTO action_codes (code, description) VALUES ('5633', 'Steel Framing–light gauge–high wage');
INSERT INTO action_codes (code, description) VALUES ('6204', 'Drilling');
INSERT INTO action_codes (code, description) VALUES ('6218(1)', 'Excavation–low wage');
INSERT INTO action_codes (code, description) VALUES ('6218(2)', 'Grading Land–low wage');
INSERT INTO action_codes (code, description) VALUES ('6218(3)', 'Land Leveling–farm lands–low wage');
INSERT INTO action_codes (code, description) VALUES ('6220(1)', 'Excavation–high wage');
INSERT INTO action_codes (code, description) VALUES ('6220(2)', 'Grading Land–high wage');
INSERT INTO action_codes (code, description) VALUES ('6220(3)', 'Land Leveling–farm lands–high wage');
INSERT INTO action_codes (code, description) VALUES ('6307', 'Sewer Construction–low wage');
INSERT INTO action_codes (code, description) VALUES ('6308', 'Sewer Construction–high wage');
INSERT INTO action_codes (code, description) VALUES ('6315(1)', 'Water Mains Construction–low wage');
INSERT INTO action_codes (code, description) VALUES ('6315(2)', 'Gas Mains Construction–low wage');
INSERT INTO action_codes (code, description) VALUES ('6316(1)', 'Water Mains Construction–high wage');
INSERT INTO action_codes (code, description) VALUES ('6316(2)', 'Gas Mains Construction–high wage');
INSERT INTO action_codes (code, description) VALUES ('6325', 'Conduit Construction');
INSERT INTO action_codes (code, description) VALUES ('6364', 'Irrigation Pipe Installation ');
INSERT INTO action_codes (code, description) VALUES ('6400', 'Fence Construction');
INSERT INTO action_codes (code, description) VALUES ('7538', 'Electric Light/Power Line Construction');
INSERT INTO action_codes (code, description) VALUES ('7605(1)', 'Burglar Alarm Installation/Repair');
INSERT INTO action_codes (code, description) VALUES ('7605(2)', 'Fire Alarm Installation/Repair');
INSERT INTO action_codes (code, description) VALUES ('7605(3)', 'Sound System Installation/Repair');
INSERT INTO action_codes (code, description) VALUES ('8018', 'Stores–wholesale');
INSERT INTO action_codes (code, description) VALUES ('8227', 'Construction/Erection Permanent Yards');
INSERT INTO action_codes (code, description) VALUES ('8232(2)', 'Building Material Dealers');
INSERT INTO action_codes (code, description) VALUES ('8742(1)', 'Salespersons–outside');
INSERT INTO action_codes (code, description) VALUES ('8810(1)', 'Clerical Office Employees');
INSERT INTO action_codes (code, description) VALUES ('9008', 'Janitorial Services');
INSERT INTO action_codes (code, description) VALUES ('9009', 'Building Operation–commercial–other');
INSERT INTO action_codes (code, description) VALUES ('9015(1)', 'Building Operation–N.O.C.–other employees');
INSERT INTO action_codes (code, description) VALUES ('9097', 'Swimming Pool Cleaning/Servicing');
INSERT INTO action_codes (code, description) VALUES ('9519(4)', 'Water Softening/Conditioning Systems');
INSERT INTO action_codes (code, description) VALUES ('9521(1)', 'House Furnishings');
INSERT INTO action_codes (code, description) VALUES ('9521(2)', 'Floor Covering');
INSERT INTO action_codes (code, description) VALUES ('9521(3)', 'Window Covering');
INSERT INTO action_codes (code, description) VALUES ('9529(2)', 'Decorating');
INSERT INTO action_codes (code, description) VALUES ('9552', 'Sign Erection/Repair');
